[package]
name = "virtual-desktop-keybinds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mki = "0.2.3"
windows = { version = "0.48.0", features = ["Win32_UI_Shell", "Win32_Foundation"] }
